export const COMMON_LOADING = 'COMMON_LOADING';
export const KEY_CONNECT_CHANGED = 'KEY_CONNECT_CHANGED';
export const ORDER_SUBMIT_RESULT = 'ORDER_SUBMIT_RESULT';
export const ORDER_TRIGGER_ORDER_FORM = 'ORDER_TRIGGER_ORDER_FORM';
export const STOCK_TRANSFER = 'STOCK_TRANSFER';
